package com.websystique.springmvc.model;
// Generated Aug 8, 2017 11:50:21 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cultivar generated by hbm2java
 */
@Entity
@Table
public class Cultivar implements java.io.Serializable {
   @Id
   @Column
	private int id;
   @Column
	private String name;
	@Column
   private String job;

	public Cultivar() {
	}

	public Cultivar(int id, String job) {
		this.id = id;
		this.job = job;
	}

	public Cultivar(int id, String name, String job) {
		this.id = id;
		this.name = name;
		this.job = job;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

}
